swagger: '2.0'
info:
  description: >-
    ## `Money`

    The `Money` archetype represents an amount of a specific `Currency`.

    ## `Currency`


    This `Currency` implements `Metric` and is `acceptedIn` one or more
    `Locales`. `Currency's` unique identifier is its `alphabeticCode`.


    At present, there are two fundamentally different types of currency -- those
    that are specified by ISO and those that are not.

    1. **`IsoCurrency`** represents a type of `Currency` with [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) definitions for

        - `name`,
        - `alphabeticCode`, and
        - `numericCode`.

    2. **`NonIsoCurrency`** represents a type of `Currency` that is _not_
    defined in any ISO specification. These types of currency might unrecognized
    or arbitrary "rewards," like American Airlines AAdvantage Miles.

    ## `Payment` and `PaymentMethod`

    The `Payment` archetype represents `Money` paid by one `Party` to another in return for goods or services. A `PaymentMethod` is a medium by which `Money` is transferred.


    ### `PaymentCard`




    ### `CreditCard`


    ### `DebitCard`


    ### `GiftCard`


    ### `Donation`


    ### `Cash` and `DigitalCurrency`



    ### `Check`



    ## Compliance with existing standards

    <table>
      <thead>
        <tr><th>Standard</th><th>Contents</th></tr>
      </thead>
      <tfoot>
      </tfoot>
      <tbody>
        <tr>
          <td><a href="http://www.omg.org/spec/CURR/1.0/PDF">OMG Currency Specification v1.0</a></td>
          <td>A standard to support international currency.</td>
        </tr>
        <tr>
          <td><a href="https://www.iso.org/iso-4217-currency-codes.html">ISO 4217</a></td>
          <td>Three- and two-letter currency codes, currency numbers, and currency names.</td>
        </tr>
        <tr>
          <td><a href="https://www.iso.org/iso-3166-country-codes.html">ISO 3166</a></td>
          <td>Two-letter country codes and country names.</td>
        </tr>
      </tbody>
    </table>


    ---

    ## About

  version: 1.0.0
  title: Money
  contact:
    email: greg@swindle.net
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: api.swindle.net
basePath: /archetypes/v1/money
tags:
  - name: Currency
    description: >-
      A Metric or standard of value for measuring Money, accepted in or or more
      Locales.
  - name: Payment
    description: >-
      Represents Money paid by one Party to another in return for goods and
      services.
  - name: Payment Method
    description: The medium by which a Payment may be made.
schemes:
  - http
  - https
externalDocs:
  description: OMG Currency Specification v1.0
  url: 'http://www.omg.org/spec/CURR/1.0/PDF'
paths:
  /currencies:
    get:
      tags:
        - Currency
      summary: Retrieve all currencies.
      description: Retrieve all currencies.
      produces:
        - application/json
        - application/xml
      operationId: getCurrencies
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              - $ref: '#/definitions/Currency'
            example:
              - alphabeticCode: USD
                definition: The monetary unit of the United States of America
                majorUnitSymbol: $
                minorUnitSymbol: ¢
                name: Dollar
                numericCode: '840'
                ratioOfMinorUnitToMajorUnit: 100
                symbol: $
                validFrom: null
                validTo: null
  '/currencies/{alphabetic-code}':
    get:
      tags:
        - Currency
      summary: Retrieve a Currency by alphabetic code.
      description: Retrieve a specific Currency by its alphabetic code.
      produces:
        - application/json
        - application/xml
      operationId: getCurrencyByAlphabeticCode
      parameters:
        - in: path
          name: alphabetic-code
          description: An alphabetic code that represents the currency.
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: >-
              http://api.swindle.net/archetypes/v1/schemas/money/currency.yaml
  /payments:
    get:
      tags:
        - Payment
      summary: Retrieve all payments.
      description: Retrieve all payments.
      produces:
        - application/json
        - application/xml
      operationId: getPayments
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              - $ref: '#/definitions/Payment'
            example:
              - alphabeticCode: USD
                definition: The monetary unit of the United States of America
                majorUnitSymbol: $
                minorUnitSymbol: ¢
                name: Dollar
                numericCode: '840'
                ratioOfMinorUnitToMajorUnit: 100
                symbol: $
                validFrom: null
                validTo: null
  /payment-methods:
    get:
      tags:
        - Payment Method
      summary: Retrieve all payment method types.
      description: Retrieve all payment method types.
      produces:
        - application/json
        - application/xml
      operationId: getPaymentMethods
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              - $ref: '#/definitions/PaymentMethod'
            example: []
definitions:
  Currency:
    allOf:
      - $ref: 'http://api.swindle.net/archetypes/v1/schemas/money/currency.yaml'
      - properties:
          name:
            description: 'The name of the `Currency`, e.g., "Pound Sterling".'
          definition:
            description: >-
              A description of the `Currency`, e.g., "The monetary unit of the
              United Kingdom".
          symbol:
            description: Synonymous with `majorUnitSymbol`.
      - title: Currency
      - description: Represents a `Metric` or standard of value for measuring Money.
  Money:
    allOf:
      - $ref: >-
          http://api.swindle.net/archetypes/v1/schemas/quantities/quantity.yaml
      - $ref:  >-
          http://api.swindle.net/archetypes/v1/schemas/money/money.yaml
      - properties:
          currency:
            $ref: >-
              http://api.swindle.net/archetypes/v1/schemas/money/currency.yaml
      - title: Money
      - description: Represents the amount of a specific Currency.
  PaymentMethod:
    allOf:
      - $ref: >-
          http://api.swindle.net/archetypes/v1/schemas/money/payment-method.yaml
      - title: PaymentMethod
  PaymentCard:
    allOf:
      - $ref: >-
          http://api.swindle.net/archetypes/v1/schemas/money/payment-card.yaml
      - title: PaymentCard
      - description: >-
          Represents a physical token such as a plastic card that authorizes the
          Party identified on it to charge the cost of goods and services to an
          account.
  Payment:
    allOf:
      - $ref: >-
          http://api.swindle.net/archetypes/v1/schemas/money/payment.yaml
      - title: Payment
